enum effect_param_datatype {
    PARAM_DATATYPE_UNKNOWN,
    PARAM_DATATYPE_AUDIOLEVEL,
    PARAM_DATATYPE_BOOL,
    PARAM_DATATYPE_COLOR_ALPHA,
    PARAM_DATATYPE_DOUBLE,
    PARAM_DATATYPE_IMAGE,
    PARAM_DATATYPE_INT,
    PARAM_DATATYPE_LIST_INT,
    PARAM_DATATYPE_SOURCE,
    PARAM_DATATYPE_TEXT,
};
